/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : bigint,
  'maxSeats' : bigint,
  'registeredCount' : bigint,
  'name' : string,
  'description' : string,
  'setId' : bigint,
  'faculty' : string,
  'dateRange' : string,
}
export interface StudentRegistration {
  'studentId' : string,
  'name' : string,
  'email' : string,
  'courseSet1Id' : bigint,
  'courseSet2Id' : bigint,
}
export interface _SERVICE {
  'changeAdminPassword' : ActorMethod<[string, string], boolean>,
  'getAllCourses' : ActorMethod<[], Array<Course>>,
  'getAllRegistrations' : ActorMethod<[string], Array<StudentRegistration>>,
  'getCoursesBySet' : ActorMethod<[bigint], Array<Course>>,
  'registerStudent' : ActorMethod<
    [string, string, string, bigint, bigint],
    string
  >,
  'updateCourse' : ActorMethod<
    [string, bigint, string, string, string, string],
    boolean
  >,
  'verifyAdminPassword' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];