/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Course = IDL.Record({
  'id' : IDL.Nat,
  'maxSeats' : IDL.Nat,
  'registeredCount' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'setId' : IDL.Nat,
  'faculty' : IDL.Text,
  'dateRange' : IDL.Text,
});
export const StudentRegistration = IDL.Record({
  'studentId' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'courseSet1Id' : IDL.Nat,
  'courseSet2Id' : IDL.Nat,
});

export const idlService = IDL.Service({
  'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getAllRegistrations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(StudentRegistration)],
      [],
    ),
  'getCoursesBySet' : IDL.Func([IDL.Nat], [IDL.Vec(Course)], ['query']),
  'registerStudent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'updateCourse' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Course = IDL.Record({
    'id' : IDL.Nat,
    'maxSeats' : IDL.Nat,
    'registeredCount' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'setId' : IDL.Nat,
    'faculty' : IDL.Text,
    'dateRange' : IDL.Text,
  });
  const StudentRegistration = IDL.Record({
    'studentId' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'courseSet1Id' : IDL.Nat,
    'courseSet2Id' : IDL.Nat,
  });
  
  return IDL.Service({
    'changeAdminPassword' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'getAllCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getAllRegistrations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(StudentRegistration)],
        [],
      ),
    'getCoursesBySet' : IDL.Func([IDL.Nat], [IDL.Vec(Course)], ['query']),
    'registerStudent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'updateCourse' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };